//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : MizePortal
	/// Data Source    : sql.mizegroup.com
	/// Server Version : 10.50.6220
	/// </summary>
	public partial class MizePortalDB : LinqToDB.Data.DataConnection
	{
		public ITable<AttendanceDetail>       AttendanceDetails       { get { return this.GetTable<AttendanceDetail>(); } }
		public ITable<AttendanceSummary>      AttendanceSummaries     { get { return this.GetTable<AttendanceSummary>(); } }
		public ITable<Availability>           Availabilities          { get { return this.GetTable<Availability>(); } }
		public ITable<Branch>                 Branches                { get { return this.GetTable<Branch>(); } }
		public ITable<Client>                 Clients                 { get { return this.GetTable<Client>(); } }
		public ITable<ClientContractDiscount> ClientContractDiscounts { get { return this.GetTable<ClientContractDiscount>(); } }
		public ITable<ClientsAction>          ClientsActions          { get { return this.GetTable<ClientsAction>(); } }
		public ITable<ClientWarehouse>        ClientWarehouses        { get { return this.GetTable<ClientWarehouse>(); } }
		public ITable<ErpPriceList>           ErpPriceLists           { get { return this.GetTable<ErpPriceList>(); } }
		public ITable<MunifPartsSalesAvg>     MunifPartsSalesAvgs     { get { return this.GetTable<MunifPartsSalesAvg>(); } }
		public ITable<MunifStock>             MunifStocks             { get { return this.GetTable<MunifStock>(); } }
		public ITable<MzscUser>               MzscUsers               { get { return this.GetTable<MzscUser>(); } }
		public ITable<NpVstock>               NpVstocks               { get { return this.GetTable<NpVstock>(); } }
		public ITable<PartCarmodel>           PartCarmodels           { get { return this.GetTable<PartCarmodel>(); } }
		public ITable<PartCarmodelsSumm>      PartCarmodelsSumms      { get { return this.GetTable<PartCarmodelsSumm>(); } }
		public ITable<PartsOrigin>            PartsOrigins            { get { return this.GetTable<PartsOrigin>(); } }
		public ITable<Product>                Products                { get { return this.GetTable<Product>(); } }
		public ITable<ProductSub>             ProductSubs             { get { return this.GetTable<ProductSub>(); } }
		public ITable<Signage>                Signages                { get { return this.GetTable<Signage>(); } }
		public ITable<SparatRootFile>         SparatRootFiles         { get { return this.GetTable<SparatRootFile>(); } }
		public ITable<SparatStandardMaster>   SparatStandardMasters   { get { return this.GetTable<SparatStandardMaster>(); } }
		public ITable<SparatTable>            SparatTables            { get { return this.GetTable<SparatTable>(); } }
		public ITable<TrioMunifStock>         TrioMunifStocks         { get { return this.GetTable<TrioMunifStock>(); } }
		public ITable<User>                   Users                   { get { return this.GetTable<User>(); } }
		public ITable<UserSCenter>            UserSCenters            { get { return this.GetTable<UserSCenter>(); } }
		public ITable<Warehouse>              Warehouses              { get { return this.GetTable<Warehouse>(); } }

		public MizePortalDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MizePortalDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MizePortalDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MizePortalDB(LinqToDBConnectionOptions<MizePortalDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#region Table Functions

		#region FnGetMunifStockForClientSummarized

		[Sql.TableFunction(Schema="dbo", Name="fn_GetMunifStockForClient_Summarized")]
		public ITable<FnGetMunifStockForClientSummarizedResult> FnGetMunifStockForClientSummarized(int? @clientId)
		{
			return this.GetTable<FnGetMunifStockForClientSummarizedResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@clientId);
		}

		public partial class FnGetMunifStockForClientSummarizedResult
		{
			public string   PartNumber { get; set; }
			public string   Name       { get; set; }
			public decimal? soh        { get; set; }
			public decimal? Price      { get; set; }
			public string   Brand      { get; set; }
		}

		#endregion

		#region Splitstring

		[Sql.TableFunction(Schema="dbo", Name="splitstring")]
		public ITable<SplitstringResult> Splitstring(string @stringToSplit, char? @char_dilimiter)
		{
			return this.GetTable<SplitstringResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@stringToSplit,
				@char_dilimiter);
		}

		public partial class SplitstringResult
		{
			public string Name { get; set; }
		}

		#endregion

		#endregion
	}

	[Table(Schema="dbo", Name="AttendanceDetails")]
	public partial class AttendanceDetail
	{
		[Column(),                 NotNull    ] public decimal EmpNo         { get; set; } // decimal(18, 0)
		[Column(),                 NotNull    ] public string  EmpName       { get; set; } // nvarchar(403)
		[Column(),                    Nullable] public string  SecDesc       { get; set; } // nvarchar(50)
		[Column(),                    Nullable] public char?   AreaCode      { get; set; } // nvarchar(1)
		[Column("C_Date"),            Nullable] public string  CDate         { get; set; } // nvarchar(10)
		[Column("day_Name"),          Nullable] public string  DayName       { get; set; } // nvarchar(30)
		[Column("C_Time1"),           Nullable] public string  CTime1        { get; set; } // varchar(8)
		[Column("LakeIn_Minute"),     Nullable] public string  LakeInMinute  { get; set; } // nvarchar(61)
		[Column("C_Time1_1"),         Nullable] public string  CTime11       { get; set; } // varchar(8)
		[Column("C_Time2_0"),         Nullable] public string  CTime20       { get; set; } // varchar(8)
		[Column("C_Time2"),           Nullable] public string  CTime2        { get; set; } // varchar(8)
		[Column("LakeOut_Minute"),    Nullable] public string  LakeOutMinute { get; set; } // nvarchar(61)
		[Column(),                 NotNull    ] public string  Dur           { get; set; } // nvarchar(30)
		[Column("is_free"),           Nullable] public string  IsFree        { get; set; } // varchar(3)
		[Column("isAbsent"),       NotNull    ] public char    IsAbsent      { get; set; } // varchar(1)
	}

	[Table(Schema="dbo", Name="AttendanceSummary")]
	public partial class AttendanceSummary
	{
		[Column(),                 NotNull    ] public decimal EmpNo         { get; set; } // decimal(18, 0)
		[Column(),                 NotNull    ] public string  EmpName       { get; set; } // nvarchar(403)
		[Column(),                    Nullable] public string  SecDesc       { get; set; } // nvarchar(50)
		[Column(),                    Nullable] public char?   AreaCode      { get; set; } // nvarchar(1)
		[Column("days_No"),        NotNull    ] public int     DaysNo        { get; set; } // int
		[Column("LakeIn_Minute"),  NotNull    ] public string  LakeInMinute  { get; set; } // nvarchar(61)
		[Column("abs_Days"),       NotNull    ] public int     AbsDays       { get; set; } // int
		[Column("LakeOut_Minute"), NotNull    ] public string  LakeOutMinute { get; set; } // nvarchar(61)
		[Column("cntOneFinger"),      Nullable] public int?    CntOneFinger  { get; set; } // int
	}

	[Table(Schema="dbo", Name="Availability")]
	public partial class Availability
	{
		[PrimaryKey(1), NotNull    ] public string PartNumber { get; set; } // nvarchar(150)
		[PrimaryKey(2), NotNull    ] public string BranchId   { get; set; } // varchar(50)
		[Column,           Nullable] public int?   Quantity   { get; set; } // int
	}

	[Table(Schema="dbo", Name="Branch")]
	public partial class Branch
	{
		[PrimaryKey, NotNull    ] public string BranchId   { get; set; } // varchar(50)
		[Column,        Nullable] public string BranchName { get; set; } // nvarchar(350)
		[Column,        Nullable] public string CityName   { get; set; } // nvarchar(250)
	}

	[Table(Schema="dbo", Name="Clients")]
	public partial class Client
	{
		[Column("clientId"),      PrimaryKey,  NotNull] public int       ClientId      { get; set; } // int
		[Column("clientName"),       Nullable         ] public string    ClientName    { get; set; } // nvarchar(500)
		[Column("isActive"),         Nullable         ] public bool?     IsActive      { get; set; } // bit
		[Column("apiKey"),           Nullable         ] public string    ApiKey        { get; set; } // nvarchar(max)
		[Column("keyExpireDate"),    Nullable         ] public DateTime? KeyExpireDate { get; set; } // date
		[Column("accNo"),            Nullable         ] public int?      AccNo         { get; set; } // int
		[Column("clientNumber"),     Nullable         ] public int?      ClientNumber  { get; set; } // int
		[Column("discOrCost"),       Nullable         ] public string    DiscOrCost    { get; set; } // varchar(50)
	}

	[Table(Schema="dbo", Name="ClientContractDiscounts")]
	public partial class ClientContractDiscount
	{
		[Column("id"),               PrimaryKey, Identity] public int      Id               { get; set; } // int
		[Column("clientId"),         Nullable            ] public int?     ClientId         { get; set; } // int
		[Column("markCode"),         Nullable            ] public string   MarkCode         { get; set; } // nvarchar(50)
		[Column("discPer"),          Nullable            ] public double?  DiscPer          { get; set; } // float
		[Column("partGrade"),        Nullable            ] public string   PartGrade        { get; set; } // varchar(50)
		[Column("manufacturerName"), Nullable            ] public string   ManufacturerName { get; set; } // nvarchar(150)
		[Column("isActive"),         Nullable            ] public bool?    IsActive         { get; set; } // bit
		[Column("costPlus"),         Nullable            ] public double?  CostPlus         { get; set; } // float
		[Column("taxRate"),          Nullable            ] public decimal? TaxRate          { get; set; } // decimal(18, 2)
		[Column("warehouseCode"),    Nullable            ] public int?     WarehouseCode    { get; set; } // int
	}

	[Table(Schema="dbo", Name="ClientsActions")]
	public partial class ClientsAction
	{
		[Column("id"),         PrimaryKey,  NotNull] public int    Id         { get; set; } // int
		[Column("apiKey"),        Nullable         ] public string ApiKey     { get; set; } // varchar(50)
		[Column("actionCode"),    Nullable         ] public string ActionCode { get; set; } // varchar(50)
		[Column("isActive"),      Nullable         ] public bool?  IsActive   { get; set; } // bit
	}

	[Table(Schema="dbo", Name="ClientWarehouses")]
	public partial class ClientWarehouse
	{
		[Column("clientId"),      PrimaryKey(1), NotNull] public int ClientId      { get; set; } // int
		[Column("warehouseCode"), PrimaryKey(2), NotNull] public int WarehouseCode { get; set; } // int
	}

	[Table(Schema="dbo", Name="ERP_PRICE_LIST")]
	public partial class ErpPriceList
	{
		[Column("ITEM_CODE"), Nullable] public string   ItemCode { get; set; } // varchar(100)
		[Column(),            Nullable] public decimal? RSP      { get; set; } // numeric(18, 2)
		[Column("PRICE_ONE"), Nullable] public decimal? PriceOne { get; set; } // numeric(18, 2)
	}

	[Table(Schema="dbo", Name="MunifPartsSalesAvg")]
	public partial class MunifPartsSalesAvg
	{
		[Column("ITEM_CODE"), Nullable] public string   ItemCode { get; set; } // varchar(100)
		[Column("PART_CODE"), Nullable] public string   PartCode { get; set; } // varchar(8000)
		[Column("ITEM_DESC"), Nullable] public string   ItemDesc { get; set; } // nvarchar(500)
		[Column("PART_AVG"),  Nullable] public decimal? PartAvg  { get; set; } // decimal(38, 6)
	}

	[Table(Schema="dbo", Name="MunifStock")]
	public partial class MunifStock
	{
		[Column(),            PrimaryKey,  Identity] public int       Id              { get; set; } // int
		[Column(),               Nullable          ] public int?      CategoryId      { get; set; } // int
		[Column(),               Nullable          ] public string    Name            { get; set; } // nvarchar(250)
		[Column(),               Nullable          ] public string    Description     { get; set; } // nvarchar(350)
		[Column(),               Nullable          ] public decimal?  RetailPrice     { get; set; } // decimal(18, 2)
		[Column(),               Nullable          ] public DateTime? CreatedDate     { get; set; } // datetime
		[Column(),               Nullable          ] public string    PartNumber      { get; set; } // nvarchar(150)
		[Column(),               Nullable          ] public decimal?  WholesalesPrice { get; set; } // decimal(18, 2)
		[Column(),               Nullable          ] public string    Brand           { get; set; } // nvarchar(150)
		[Column("vendorId"),     Nullable          ] public int?      VendorId        { get; set; } // int
		[Column(),               Nullable          ] public bool?     Available       { get; set; } // bit
		[Column("clientId"),     Nullable          ] public int?      ClientId        { get; set; } // int
		[Column("soh"),          Nullable          ] public decimal?  Soh             { get; set; } // decimal(18, 0)
		[Column("mzSoh"),        Nullable          ] public decimal?  MzSoh           { get; set; } // decimal(18, 0)
		[Column(),               Nullable          ] public decimal?  PriceOne        { get; set; } // decimal(18, 2)
		[Column(),               Nullable          ] public decimal?  PriceTwo        { get; set; } // decimal(18, 2)
		[Column(),            NotNull              ] public int       WarehouseId     { get; set; } // int
		[Column("unitCost"),     Nullable          ] public decimal?  UnitCost        { get; set; } // decimal(18, 2)
		[Column("part_code"),    Nullable          ] public string    PartCode        { get; set; } // varchar(50)
		[Column(),               Nullable          ] public string    CarModels       { get; set; } // nvarchar(max)
		[Column(),               Nullable          ] public string    ProdFrom        { get; set; } // nvarchar(25)
		[Column(),               Nullable          ] public string    ProdTo          { get; set; } // nvarchar(25)
	}

	[Table(Schema="dbo", Name="MzscUsers")]
	public partial class MzscUser
	{
		[Column("userId"),   PrimaryKey,  NotNull] public int    UserId   { get; set; } // int
		[Column("userName"),    Nullable         ] public string UserName { get; set; } // nvarchar(150)
		[Column("empNo"),       Nullable         ] public int?   EmpNo    { get; set; } // int
	}

	[Table(Schema="dbo", Name="NP_VSTOCK")]
	public partial class NpVstock
	{
		[Column("PART_CODE"),       Nullable] public string   PartCode    { get; set; } // nvarchar(50)
		[Column("PART_DESC"),       Nullable] public string   PartDesc    { get; set; } // nvarchar(250)
		[Column("PART_ORG"),        Nullable] public string   PartOrg     { get; set; } // nvarchar(50)
		[Column(),                  Nullable] public string   FACTIVITY   { get; set; } // nvarchar(1000)
		[Column("ITEM_DESC"),       Nullable] public string   ItemDesc    { get; set; } // nvarchar(500)
		[Column("PRICE_AMOUNT"),    Nullable] public decimal? PriceAmount { get; set; } // decimal(18, 5)
		[Column("SUG_PRICE"),       Nullable] public decimal? SugPrice    { get; set; } // numeric(38, 2)
		[Column(),               NotNull    ] public int      SOH         { get; set; } // int
		[Column("VENDOR_ID"),    NotNull    ] public int      VendorId    { get; set; } // int
	}

	[Table(Schema="dbo", Name="PartCarmodels")]
	public partial class PartCarmodel
	{
		[Column("part_code"), NotNull    ] public string PartCode  { get; set; } // nvarchar(15)
		[Column("carmodels"),    Nullable] public string Carmodels { get; set; } // varchar(max)
	}

	[Table(Schema="dbo", Name="part_carmodels_summ")]
	public partial class PartCarmodelsSumm
	{
		[Column("part_code"),   NotNull    ] public string PartCode   { get; set; } // nvarchar(15)
		[Column("cars_models"),    Nullable] public string CarsModels { get; set; } // nvarchar(201)
		[Column("prod_start"),     Nullable] public string ProdStart  { get; set; } // nvarchar(10)
		[Column("prod_end"),       Nullable] public string ProdEnd    { get; set; } // nvarchar(10)
	}

	[Table(Schema="dbo", Name="PartsOrigin")]
	public partial class PartsOrigin
	{
		[Column("ITEM_CODE"), Nullable] public string ItemCode { get; set; } // varchar(100)
		[Column(),            Nullable] public string ORIGIN   { get; set; } // nvarchar(250)
	}

	[Table(Schema="dbo", Name="Product")]
	public partial class Product
	{
		[Column(),           PrimaryKey, Identity] public int       Id              { get; set; } // int
		[Column(),           Nullable            ] public int?      CategoryId      { get; set; } // int
		[Column(),           Nullable            ] public string    Name            { get; set; } // nvarchar(250)
		[Column(),           Nullable            ] public string    Description     { get; set; } // nvarchar(350)
		[Column(),           Nullable            ] public decimal?  RetailPrice     { get; set; } // decimal(18, 2)
		[Column(),           Nullable            ] public DateTime? CreatedDate     { get; set; } // datetime
		[Column(),           Nullable            ] public string    PartNumber      { get; set; } // nvarchar(150)
		[Column(),           Nullable            ] public decimal?  WholesalesPrice { get; set; } // decimal(18, 2)
		[Column(),           Nullable            ] public string    Brand           { get; set; } // nvarchar(150)
		[Column("vendorId"), Nullable            ] public int?      VendorId        { get; set; } // int
		[Column(),           Nullable            ] public bool?     Available       { get; set; } // bit
		[Column("clientId"), Nullable            ] public int?      ClientId        { get; set; } // int
		[Column("soh"),      Nullable            ] public decimal?  Soh             { get; set; } // decimal(18, 0)
		[Column("mzSoh"),    Nullable            ] public decimal?  MzSoh           { get; set; } // decimal(18, 0)
		[Column(),           Nullable            ] public decimal?  PriceOne        { get; set; } // decimal(18, 2)
		[Column(),           Nullable            ] public decimal?  PriceTwo        { get; set; } // decimal(18, 2)
	}

	[Table(Schema="dbo", Name="ProductSub")]
	public partial class ProductSub
	{
		[Identity          ] public int      Id           { get; set; } // int
		[Column,   Nullable] public string   PartNumber   { get; set; } // nvarchar(150)
		[Column,   Nullable] public string   SubPart      { get; set; } // nvarchar(150)
		[Column,   Nullable] public decimal? SubPartPrice { get; set; } // decimal(18, 2)
		[Column,   Nullable] public decimal? SubPartSoh   { get; set; } // decimal(18, 0)
		[Column,   Nullable] public string   PartBrand    { get; set; } // nvarchar(50)
		[Column,   Nullable] public string   SubBrand     { get; set; } // nvarchar(50)
	}

	[Table(Schema="dbo", Name="Signage")]
	public partial class Signage
	{
		[Column("id"),           PrimaryKey,  NotNull] public int    Id           { get; set; } // int
		[Column("signageUrl"),      Nullable         ] public string SignageUrl   { get; set; } // nvarchar(max)
		[Column("duration"),        Nullable         ] public int?   Duration     { get; set; } // int
		[Column("isActive"),        Nullable         ] public bool?  IsActive     { get; set; } // bit
		[Column("displayOrder"),    Nullable         ] public int?   DisplayOrder { get; set; } // int
	}

	[Table(Schema="dbo", Name="SparatRootFile")]
	public partial class SparatRootFile
	{
		[Column("STANDARED_PART"), Nullable] public string StandaredPart { get; set; } // varchar(150)
		[Column("PART_CODE"),      Nullable] public string PartCode      { get; set; } // varchar(100)
		[Column(),                 Nullable] public string BRAND         { get; set; } // varchar(50)
		[Column(),                 Nullable] public string CAR           { get; set; } // varchar(50)
		[Column("FROM_YEAR"),      Nullable] public int?   FromYear      { get; set; } // int
		[Column("TO_YEAR"),        Nullable] public int?   ToYear        { get; set; } // int
	}

	[Table(Schema="dbo", Name="SparatStandardMaster")]
	public partial class SparatStandardMaster
	{
		[Column("standardPart"), Nullable] public string StandardPart { get; set; } // nvarchar(250)
		[Column("category"),     Nullable] public string Category     { get; set; } // nvarchar(250)
	}

	[Table(Schema="dbo", Name="SparatTable")]
	public partial class SparatTable
	{
		[Column("carCategory"),     Nullable] public string   CarCategory     { get; set; } // varchar(50)
		[Column("brand"),           Nullable] public string   Brand           { get; set; } // varchar(50)
		[Column("model"),           Nullable] public string   Model           { get; set; } // varchar(50)
		[Column("yearFrom"),        Nullable] public string   YearFrom        { get; set; } // varchar(50)
		[Column("yearTo"),          Nullable] public string   YearTo          { get; set; } // varchar(50)
		[Column("partCategory"),    Nullable] public string   PartCategory    { get; set; } // varchar(50)
		[Column("standardPart"),    Nullable] public string   StandardPart    { get; set; } // varchar(150)
		[Column("partNumber"),      Nullable] public string   PartNumber      { get; set; } // varchar(150)
		[Column("origin"),          Nullable] public string   Origin          { get; set; } // varchar(50)
		[Column("price"),           Nullable] public decimal? Price           { get; set; } // decimal(18, 2)
		[Column("stockQuantity"),   Nullable] public decimal? StockQuantity   { get; set; } // decimal(18, 0)
		[Column("warranty"),        Nullable] public int?     Warranty        { get; set; } // int
		[Column("disassemblyCost"), Nullable] public decimal? DisassemblyCost { get; set; } // decimal(18, 0)
		[Column("notes"),           Nullable] public string   Notes           { get; set; } // nchar(10)
	}

	[Table(Schema="dbo", Name="Trio_MunifStock")]
	public partial class TrioMunifStock
	{
		[Column, NotNull    ] public string   PartNo    { get; set; } // nvarchar(50)
		[Column, NotNull    ] public double   Price     { get; set; } // float
		[Column,    Nullable] public string   Category  { get; set; } // nvarchar(1000)
		[Column,    Nullable] public decimal? Available { get; set; } // decimal(38, 0)
	}

	[Table(Schema="dbo", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity] public int    Id           { get; set; } // int
		[Column,     Nullable] public string UserName     { get; set; } // nvarchar(50)
		[Column,     Nullable] public string Password     { get; set; } // nvarchar(50)
		[Column,     Nullable] public bool?  IsActive     { get; set; } // bit
		[Column,     Nullable] public string Applications { get; set; } // nvarchar(250)
		[Column,     Nullable] public string Roles        { get; set; } // varchar(350)
	}

	[Table(Schema="dbo", Name="UserSCenter")]
	public partial class UserSCenter
	{
		[Column("userId"),     PrimaryKey(1), NotNull] public int   UserId     { get; set; } // int
		[Column("branchId"),   PrimaryKey(2), NotNull] public int   BranchId   { get; set; } // int
		[Column("canViewAll"),    Nullable           ] public char? CanViewAll { get; set; } // char(1)
		[Column("WSHC_SEQ"),      Nullable           ] public int?  WshcSeq    { get; set; } // int
		[Column("WSHC_TYPE"),     Nullable           ] public int?  WshcType   { get; set; } // int
		[Column("TECH_SEQ"),      Nullable           ] public int?  TechSeq    { get; set; } // int
		[Column("TECH_TYPE"),     Nullable           ] public int?  TechType   { get; set; } // int
		[Column("isActive"),      Nullable           ] public char? IsActive   { get; set; } // char(1)
	}

	[Table(Schema="dbo", Name="Warehouses")]
	public partial class Warehouse
	{
		[PrimaryKey, NotNull    ] public string BranchId   { get; set; } // varchar(50)
		[Column,        Nullable] public string BranchName { get; set; } // nvarchar(350)
		[Column,        Nullable] public string CityName   { get; set; } // nvarchar(250)
	}

	public static partial class MizePortalDBStoredProcedures
	{
		#region MkenaPartsTableBuild

		public static int MkenaPartsTableBuild(this MizePortalDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[Mkena_PartsTable_Build]");
		}

		#endregion

		#region GetMunifStockForClientDetailed

		public static IEnumerable<GetMunifStockForClientDetailedResult> GetMunifStockForClientDetailed(this MizePortalDB dataConnection, int? @clientId)
		{
			var parameters = new []
			{
				new DataParameter("@clientId", @clientId, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<GetMunifStockForClientDetailedResult>("[dbo].[GetMunifStockForClient_Detailed]", parameters);
		}

		public partial class GetMunifStockForClientDetailedResult
		{
			public int       Id              { get; set; }
			public int?      CategoryId      { get; set; }
			public string    Name            { get; set; }
			public string    Description     { get; set; }
			public decimal?  RetailPrice     { get; set; }
			public DateTime? CreatedDate     { get; set; }
			public string    PartNumber      { get; set; }
			public decimal?  WholesalesPrice { get; set; }
			public int?      vendorId        { get; set; }
			public bool?     Available       { get; set; }
			public int?      clientId        { get; set; }
			public decimal?  soh             { get; set; }
			public decimal?  mzSoh           { get; set; }
			public decimal?  PriceOne        { get; set; }
			public decimal?  PriceTwo        { get; set; }
			public int       WarehouseId     { get; set; }
			public decimal?  unitCost        { get; set; }
			public string    Brand           { get; set; }
		}

		#endregion

		#region GetMunifStockForClientSummarized

		public static IEnumerable<GetMunifStockForClientSummarizedResult> GetMunifStockForClientSummarized(this MizePortalDB dataConnection, int? @clientId)
		{
			var parameters = new []
			{
				new DataParameter("@clientId", @clientId, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<GetMunifStockForClientSummarizedResult>("[dbo].[GetMunifStockForClient_Summarized]", parameters);
		}

		public partial class GetMunifStockForClientSummarizedResult
		{
			public string   PartNumber  { get; set; }
			public string   Name        { get; set; }
			public decimal? soh         { get; set; }
			public decimal? Price       { get; set; }
			public string   Brand       { get; set; }
			public decimal? RetailPrice { get; set; }
		}

		#endregion

		#region CheckClientValidityApiKey

		public static IEnumerable<CheckClientValidityApiKeyResult> CheckClientValidityApiKey(this MizePortalDB dataConnection, string @apikey)
		{
			var parameters = new []
			{
				new DataParameter("@apikey", @apikey, LinqToDB.DataType.VarChar)
				{
					Size = 150
				}
			};

			var ms = dataConnection.MappingSchema;

			return dataConnection.QueryProc(dataReader =>
				new CheckClientValidityApiKeyResult
				{
					Column1 = Converter.ChangeTypeTo<int>(dataReader.GetValue(0), ms),
				},
				"[dbo].[CheckClientValidityApiKey]", parameters);
		}

		public partial class CheckClientValidityApiKeyResult
		{
			[Column("")] public int Column1 { get; set; }
		}

		#endregion

		#region GetClientIdByApiKey

		public static IEnumerable<GetClientIdByApiKeyResult> GetClientIdByApiKey(this MizePortalDB dataConnection, string @apikey)
		{
			var parameters = new []
			{
				new DataParameter("@apikey", @apikey, LinqToDB.DataType.VarChar)
				{
					Size = 150
				}
			};

			return dataConnection.QueryProc<GetClientIdByApiKeyResult>("[dbo].[GetClientIdByApiKey]", parameters);
		}

		public partial class GetClientIdByApiKeyResult
		{
			public int? clientId { get; set; }
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Availability Find(this ITable<Availability> table, string PartNumber, string BranchId)
		{
			return table.FirstOrDefault(t =>
				t.PartNumber == PartNumber &&
				t.BranchId   == BranchId);
		}

		public static Branch Find(this ITable<Branch> table, string BranchId)
		{
			return table.FirstOrDefault(t =>
				t.BranchId == BranchId);
		}

		public static Client Find(this ITable<Client> table, int ClientId)
		{
			return table.FirstOrDefault(t =>
				t.ClientId == ClientId);
		}

		public static ClientContractDiscount Find(this ITable<ClientContractDiscount> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ClientsAction Find(this ITable<ClientsAction> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ClientWarehouse Find(this ITable<ClientWarehouse> table, int ClientId, int WarehouseCode)
		{
			return table.FirstOrDefault(t =>
				t.ClientId      == ClientId &&
				t.WarehouseCode == WarehouseCode);
		}

		public static MunifStock Find(this ITable<MunifStock> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static MzscUser Find(this ITable<MzscUser> table, int UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}

		public static Product Find(this ITable<Product> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Signage Find(this ITable<Signage> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static User Find(this ITable<User> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UserSCenter Find(this ITable<UserSCenter> table, int UserId, int BranchId)
		{
			return table.FirstOrDefault(t =>
				t.UserId   == UserId &&
				t.BranchId == BranchId);
		}

		public static Warehouse Find(this ITable<Warehouse> table, string BranchId)
		{
			return table.FirstOrDefault(t =>
				t.BranchId == BranchId);
		}
	}
}
