//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : MizeCRM
	/// Data Source    : sql.mizegroup.com
	/// Server Version : 10.50.6220
	/// </summary>
	public partial class MizeCRMDB : LinqToDB.Data.DataConnection
	{
		public ITable<Appointment>                     Appointments                      { get { return this.GetTable<Appointment>(); } }
		public ITable<Complaint>                       Complaints                        { get { return this.GetTable<Complaint>(); } }
		public ITable<ComplaintHistory>                ComplaintHistories                { get { return this.GetTable<ComplaintHistory>(); } }
		public ITable<ContactLoyaltyPointsSyncHistory> ContactLoyaltyPointsSyncHistories { get { return this.GetTable<ContactLoyaltyPointsSyncHistory>(); } }
		public ITable<ContactSale>                     ContactSales                      { get { return this.GetTable<ContactSale>(); } }
		public ITable<JobOrder>                        JobOrders                         { get { return this.GetTable<JobOrder>(); } }
		public ITable<SurveyDetail>                    SurveyDetails                     { get { return this.GetTable<SurveyDetail>(); } }
		public ITable<SurveyMaster>                    SurveyMasters                     { get { return this.GetTable<SurveyMaster>(); } }
		public ITable<SurveyQuestion>                  SurveyQuestions                   { get { return this.GetTable<SurveyQuestion>(); } }
		public ITable<SurveyQuestionOption>            SurveyQuestionOptions             { get { return this.GetTable<SurveyQuestionOption>(); } }
		public ITable<VwContact>                       VwContacts                        { get { return this.GetTable<VwContact>(); } }
		public ITable<VwContactSale>                   VwContactSales                    { get { return this.GetTable<VwContactSale>(); } }
		public ITable<VwQuestionDefaultOption>         VwQuestionDefaultOptions          { get { return this.GetTable<VwQuestionDefaultOption>(); } }
		public ITable<VwSurveyRegister>                VwSurveyRegisters                 { get { return this.GetTable<VwSurveyRegister>(); } }
		public ITable<VwSurveySumRate>                 VwSurveySumRates                  { get { return this.GetTable<VwSurveySumRate>(); } }

		public MizeCRMDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MizeCRMDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MizeCRMDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MizeCRMDB(LinqToDBConnectionOptions<MizeCRMDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Appointment")]
	public partial class Appointment
	{
		[PrimaryKey, Identity   ] public int      Id            { get; set; } // int
		[Column,     NotNull    ] public string   ReservationNo { get; set; } // varchar(150)
		[Column,        Nullable] public string   Mobile        { get; set; } // nvarchar(50)
		[Column,        Nullable] public string   CustomerName  { get; set; } // nvarchar(350)
		[Column,     NotNull    ] public DateTime Date          { get; set; } // date
		[Column,     NotNull    ] public string   Time          { get; set; } // varchar(50)
		[Column,     NotNull    ] public int      BranchId      { get; set; } // int
		[Column,     NotNull    ] public bool     Reserved      { get; set; } // bit
	}

	[Table(Schema="dbo", Name="Complaints")]
	public partial class Complaint
	{
		[Column("id"),            PrimaryKey,  NotNull] public int    Id            { get; set; } // int
		[Column("complaintTile"),    Nullable         ] public string ComplaintTile { get; set; } // nvarchar(350)
		[Column("description"),      Nullable         ] public string Description   { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="ComplaintHistory")]
	public partial class ComplaintHistory
	{
		[Column("id"),              PrimaryKey, Identity] public int       Id              { get; set; } // int
		[Column("ser"),             Nullable            ] public string    Ser             { get; set; } // varchar(50)
		[Column("mobileNo"),        Nullable            ] public string    MobileNo        { get; set; } // varchar(50)
		[Column("branchId"),        Nullable            ] public int?      BranchId        { get; set; } // int
		[Column("userId"),          Nullable            ] public int?      UserId          { get; set; } // int
		[Column("createdUtc"),      Nullable            ] public DateTime? CreatedUtc      { get; set; } // datetime
		[Column("complaintId"),     Nullable            ] public int?      ComplaintId     { get; set; } // int
		[Column("fullDescription"), Nullable            ] public string    FullDescription { get; set; } // nvarchar(max)
		[Column("empNo"),           Nullable            ] public int?      EmpNo           { get; set; } // int
		[Column("priority"),        Nullable            ] public string    Priority        { get; set; } // varchar(50)
	}

	[Table(Schema="dbo", Name="ContactLoyaltyPointsSyncHistory")]
	public partial class ContactLoyaltyPointsSyncHistory
	{
		[Column(),                PrimaryKey, Identity] public int       ID           { get; set; } // int
		[Column("CUS_MOBILE"),    Nullable            ] public string    CusMobile    { get; set; } // varchar(50)
		[Column("POINTS_AMOUNT"), Nullable            ] public decimal?  PointsAmount { get; set; } // decimal(18, 0)
		[Column("SYNC_DATE"),     Nullable            ] public DateTime? SyncDate     { get; set; } // date
	}

	[Table(Schema="dbo", Name="ContactSale")]
	public partial class ContactSale
	{
		[Column("CUS_MOBILE"),   Nullable] public string   CusMobile   { get; set; } // nvarchar(100)
		[Column("TOTAL_AMOUNT"), Nullable] public decimal? TotalAmount { get; set; } // numeric(38, 17)
	}

	[Table(Schema="dbo", Name="JOB_ORDER")]
	public partial class JobOrder
	{
		[Column(),                               Nullable] public string    SER                    { get; set; } // varchar(200)
		[Column(),                            NotNull    ] public decimal   SEQ                    { get; set; } // decimal(18, 0)
		[Column("BRANCH_ID"),                 NotNull    ] public decimal   BranchId               { get; set; } // decimal(18, 0)
		[Column("YEAR_CODE"),                 NotNull    ] public decimal   YearCode               { get; set; } // decimal(18, 0)
		[Column("USER_ID"),                      Nullable] public decimal?  UserId                 { get; set; } // decimal(18, 0)
		[Column("TR_DATE"),                      Nullable] public DateTime? TrDate                 { get; set; } // date
		[Column("ORDER_SOURCE_SUB"),             Nullable] public decimal?  OrderSourceSub         { get; set; } // decimal(18, 0)
		[Column("ORDER_STATUS"),                 Nullable] public char?     OrderStatus            { get; set; } // nvarchar(1)
		[Column("MAINT_BRANCH"),                 Nullable] public decimal?  MaintBranch            { get; set; } // decimal(18, 0)
		[Column("ESTIMATE_WORKS_DATE"),          Nullable] public DateTime? EstimateWorksDate      { get; set; } // date
		[Column(),                               Nullable] public string    NOTES                  { get; set; } // nvarchar(1000)
		[Column("MC_SEQ"),                       Nullable] public decimal?  McSeq                  { get; set; } // decimal(18, 0)
		[Column("MODULE_NO"),                    Nullable] public decimal?  ModuleNo               { get; set; } // decimal(18, 0)
		[Column("EST_H"),                        Nullable] public decimal?  EstH                   { get; set; } // decimal(18, 0)
		[Column("EST_M"),                        Nullable] public decimal?  EstM                   { get; set; } // decimal(18, 0)
		[Column("INSURANCE_ORDER"),              Nullable] public char?     InsuranceOrder         { get; set; } // nvarchar(1)
		[Column(),                               Nullable] public decimal?  ODOMETER               { get; set; } // decimal(18, 0)
		[Column("PARKING_AREA"),                 Nullable] public string    ParkingArea            { get; set; } // nvarchar(500)
		[Column("CHECK_LIST_PATH"),              Nullable] public string    CheckListPath          { get; set; } // nvarchar(500)
		[Column("FILE_PATH"),                    Nullable] public string    FilePath               { get; set; } // nvarchar(500)
		[Column("ORDER_SOURCE_MAIN"),            Nullable] public decimal?  OrderSourceMain        { get; set; } // decimal(18, 0)
		[Column("WORK_URGENCY"),                 Nullable] public char?     WorkUrgency            { get; set; } // nvarchar(1)
		[Column("TYPE_CODE"),                 NotNull    ] public decimal   TypeCode               { get; set; } // decimal(18, 0)
		[Column("ORDER_TYPE_SUB"),               Nullable] public decimal?  OrderTypeSub           { get; set; } // decimal(18, 0)
		[Column("MAINT_CENTER_SEQ"),             Nullable] public decimal?  MaintCenterSeq         { get; set; } // decimal(18, 0)
		[Column("IS_PDI_ORDER"),                 Nullable] public char?     IsPdiOrder             { get; set; } // nvarchar(1)
		[Column("Q_SEQ"),                        Nullable] public decimal?  QSeq                   { get; set; } // decimal(18, 0)
		[Column("ORDER_TYPE_MAIN"),              Nullable] public decimal?  OrderTypeMain          { get; set; } // decimal(18, 0)
		[Column("ADVISOR_SEQ"),                  Nullable] public decimal?  AdvisorSeq             { get; set; } // decimal(18, 0)
		[Column("ADVISOR_TYPE"),                 Nullable] public decimal?  AdvisorType            { get; set; } // decimal(18, 0)
		[Column("IS_WAITING_LIST"),              Nullable] public char?     IsWaitingList          { get; set; } // nvarchar(1)
		[Column("DELIVERY_PLACE"),               Nullable] public string    DeliveryPlace          { get; set; } // nvarchar(500)
		[Column("MAINT_CENTER_BRANCH"),          Nullable] public decimal?  MaintCenterBranch      { get; set; } // decimal(18, 0)
		[Column("CHASSIS_NO"),                   Nullable] public string    ChassisNo              { get; set; } // nvarchar(50)
		[Column("ACC_NO"),                       Nullable] public decimal?  AccNo                  { get; set; } // decimal(18, 0)
		[Column("ACC_TYPE"),                     Nullable] public decimal?  AccType                { get; set; } // decimal(18, 0)
		[Column("FIRST_VISIT_DATE"),             Nullable] public DateTime? FirstVisitDate         { get; set; } // date
		[Column("LAST_VISIT_DATE"),              Nullable] public DateTime? LastVisitDate          { get; set; } // date
		[Column("Q_TYPE"),                       Nullable] public decimal?  QType                  { get; set; } // decimal(18, 0)
		[Column("IS_POSTED"),                    Nullable] public char?     IsPosted               { get; set; } // nvarchar(1)
		[Column("OPEN_DATE"),                    Nullable] public DateTime? OpenDate               { get; set; } // date
		[Column("OPEN_H"),                       Nullable] public decimal?  OpenH                  { get; set; } // decimal(18, 0)
		[Column("OPEN_M"),                       Nullable] public decimal?  OpenM                  { get; set; } // decimal(18, 0)
		[Column("CLOSE_DATE"),                   Nullable] public DateTime? CloseDate              { get; set; } // date
		[Column("CLOSE_H"),                      Nullable] public decimal?  CloseH                 { get; set; } // decimal(18, 0)
		[Column("CLOSE_M"),                      Nullable] public decimal?  CloseM                 { get; set; } // decimal(18, 0)
		[Column("DELIVERY_DATE"),                Nullable] public DateTime? DeliveryDate           { get; set; } // date
		[Column("DEL_H"),                        Nullable] public decimal?  DelH                   { get; set; } // decimal(18, 0)
		[Column("DEL_M"),                        Nullable] public decimal?  DelM                   { get; set; } // decimal(18, 0)
		[Column("OLD_ODOMETER"),                 Nullable] public decimal?  OldOdometer            { get; set; } // decimal(18, 0)
		[Column("MODEL_NO"),                     Nullable] public decimal?  ModelNo                { get; set; } // decimal(18, 0)
		[Column("IS_MAINT_CONT"),                Nullable] public char?     IsMaintCont            { get; set; } // nvarchar(1)
		[Column("IS_SERVICE_PART_WARRANTY"),     Nullable] public char?     IsServicePartWarranty  { get; set; } // nvarchar(1)
		[Column("IS_REPAIR_ORDER_WARRANTY"),     Nullable] public char?     IsRepairOrderWarranty  { get; set; } // nvarchar(1)
		[Column("IS_REPAIR_RECALL_CAMPAIGN"),    Nullable] public char?     IsRepairRecallCampaign { get; set; } // nvarchar(1)
		[Column("WARRANTY_BRANCH_ID"),           Nullable] public decimal?  WarrantyBranchId       { get; set; } // decimal(18, 0)
		[Column("WARRANTY_YEAR_CODE"),           Nullable] public decimal?  WarrantyYearCode       { get; set; } // decimal(18, 0)
		[Column("WARRANTY_TYPE_CODE"),           Nullable] public decimal?  WarrantyTypeCode       { get; set; } // decimal(18, 0)
		[Column("WARRANTY_SEQ"),                 Nullable] public decimal?  WarrantySeq            { get; set; } // decimal(18, 0)
		[Column("WARRANTY_CAMPAIGN_SEQ"),        Nullable] public decimal?  WarrantyCampaignSeq    { get; set; } // decimal(18, 0)
		[Column("COMEBACK_BRANCH"),              Nullable] public decimal?  ComebackBranch         { get; set; } // decimal(18, 0)
		[Column("COMEBACK_YEAR"),                Nullable] public decimal?  ComebackYear           { get; set; } // decimal(18, 0)
		[Column("COMEBACK_TYPE"),                Nullable] public decimal?  ComebackType           { get; set; } // decimal(18, 0)
		[Column("COMEBACK_SEQ"),                 Nullable] public decimal?  ComebackSeq            { get; set; } // decimal(18, 0)
		[Column("TR_H"),                         Nullable] public decimal?  TrH                    { get; set; } // decimal(18, 0)
		[Column("TR_M"),                         Nullable] public decimal?  TrM                    { get; set; } // decimal(18, 0)
		[Column("PROFORMA_NO"),                  Nullable] public decimal?  ProformaNo             { get; set; } // decimal(18, 0)
		[Column("PROFORMA_DATE"),                Nullable] public DateTime? ProformaDate           { get; set; } // date
		[Column("PROFORMA_DISC_PERC"),           Nullable] public decimal?  ProformaDiscPerc       { get; set; } // decimal(18, 0)
		[Column("PROFORMA_DISC_VALUE"),          Nullable] public decimal?  ProformaDiscValue      { get; set; } // decimal(18, 0)
		[Column("IS_SPLIT_ACCOUNTS"),            Nullable] public char?     IsSplitAccounts        { get; set; } // nvarchar(1)
		[Column("ACCOUNT_TYPE"),                 Nullable] public char?     AccountType            { get; set; } // nvarchar(1)
		[Column("MAINT_OP_DISC_PERC"),           Nullable] public decimal?  MaintOpDiscPerc        { get; set; } // decimal(18, 0)
		[Column("MAINT_OP_DISC_VALUE"),          Nullable] public decimal?  MaintOpDiscValue       { get; set; } // decimal(18, 0)
		[Column("SPARE_DISC_PERC"),              Nullable] public decimal?  SpareDiscPerc          { get; set; } // decimal(18, 0)
		[Column("SPARE_DISC_VALUE"),             Nullable] public decimal?  SpareDiscValue         { get; set; } // decimal(18, 0)
		[Column("EXT_DISC_PERC"),                Nullable] public decimal?  ExtDiscPerc            { get; set; } // decimal(18, 0)
		[Column("EXT_DISC_VALUE"),               Nullable] public decimal?  ExtDiscValue           { get; set; } // decimal(18, 0)
		[Column("BODY_OP_DISC_PERC"),            Nullable] public decimal?  BodyOpDiscPerc         { get; set; } // decimal(18, 0)
		[Column("BODY_OP_DISC_VALUE"),           Nullable] public decimal?  BodyOpDiscValue        { get; set; } // decimal(18, 0)
		[Column("OIL_DISC_PERC"),                Nullable] public decimal?  OilDiscPerc            { get; set; } // decimal(18, 0)
		[Column("OIL_DISC_VALUE"),               Nullable] public decimal?  OilDiscValue           { get; set; } // decimal(18, 0)
		[Column("MAINT_OP_TOTAL_PRICE"),         Nullable] public decimal?  MaintOpTotalPrice      { get; set; } // decimal(18, 0)
		[Column("SPARE_TOTAL_PRICE"),            Nullable] public decimal?  SpareTotalPrice        { get; set; } // decimal(18, 0)
		[Column("EXT_TOTAL_PRICE"),              Nullable] public decimal?  ExtTotalPrice          { get; set; } // decimal(18, 0)
		[Column("BODY_OP_TOTAL_PRICE"),          Nullable] public decimal?  BodyOpTotalPrice       { get; set; } // decimal(18, 0)
		[Column("OIL_TOTAL_PRICE"),              Nullable] public decimal?  OilTotalPrice          { get; set; } // decimal(18, 0)
		[Column("MAINT_OP_NET_TOTAL"),           Nullable] public decimal?  MaintOpNetTotal        { get; set; } // decimal(18, 0)
		[Column("SPARE_NET_TOTAL"),              Nullable] public decimal?  SpareNetTotal          { get; set; } // decimal(18, 0)
		[Column("EXT_NET_TOTAL"),                Nullable] public decimal?  ExtNetTotal            { get; set; } // decimal(18, 0)
		[Column("BODY_NET_TOTAL"),               Nullable] public decimal?  BodyNetTotal           { get; set; } // decimal(18, 0)
		[Column("OIL_NET_TOTAL"),                Nullable] public decimal?  OilNetTotal            { get; set; } // decimal(18, 0)
		[Column("NET_TOTAL"),                    Nullable] public decimal?  NetTotal               { get; set; } // decimal(18, 0)
		[Column("ACCOUNT_NO"),                   Nullable] public decimal?  AccountNo              { get; set; } // decimal(18, 0)
		[Column("Q_BRANCH_ID"),                  Nullable] public decimal?  QBranchId              { get; set; } // decimal(18, 0)
		[Column("PROFORMA_ATTACH_PATH"),         Nullable] public string    ProformaAttachPath     { get; set; } // nvarchar(500)
		[Column("PROFORMA_ATTACH_FILE"),         Nullable] public string    ProformaAttachFile     { get; set; } // nvarchar(500)
		[Column("ACC_NAME"),                     Nullable] public string    AccName                { get; set; } // nvarchar(200)
		[Column("MAINT_OP_TOTAL_TAX"),           Nullable] public decimal?  MaintOpTotalTax        { get; set; } // decimal(18, 0)
		[Column("SPARE_TOTAL_TAX"),              Nullable] public decimal?  SpareTotalTax          { get; set; } // decimal(18, 0)
		[Column("EXT_TOTAL_TAX"),                Nullable] public decimal?  ExtTotalTax            { get; set; } // decimal(18, 0)
		[Column("OIL_TOTAL_TAX"),                Nullable] public decimal?  OilTotalTax            { get; set; } // decimal(18, 0)
		[Column("BODY_OP_TOTAL_TAX"),            Nullable] public decimal?  BodyOpTotalTax         { get; set; } // decimal(18, 0)
		[Column("MAINT_CONT_BRANCH"),            Nullable] public decimal?  MaintContBranch        { get; set; } // decimal(18, 0)
		[Column("MAINT_CONT_YEAR"),              Nullable] public decimal?  MaintContYear          { get; set; } // decimal(18, 0)
		[Column("MAINT_CONT_SEQ"),               Nullable] public decimal?  MaintContSeq           { get; set; } // decimal(18, 0)
		[Column("MAINT_CONT_SEQ_DTL"),           Nullable] public decimal?  MaintContSeqDtl        { get; set; } // decimal(18, 0)
		[Column("TAX_TYPE"),                     Nullable] public char?     TaxType                { get; set; } // nvarchar(1)
		[Column("DEBIT_ACCOUNT"),                Nullable] public decimal?  DebitAccount           { get; set; } // decimal(18, 0)
		[Column("MAINT_SCH_BRANCH"),             Nullable] public decimal?  MaintSchBranch         { get; set; } // decimal(18, 0)
		[Column("MAINT_SCH_YEAR"),               Nullable] public decimal?  MaintSchYear           { get; set; } // decimal(18, 0)
		[Column("MAINT_SCH_SEQ"),                Nullable] public decimal?  MaintSchSeq            { get; set; } // decimal(18, 0)
		[Column("MAINT_SCH_TR_DATE"),            Nullable] public DateTime? MaintSchTrDate         { get; set; } // date
		[Column("IS_MAINT_SCH"),                 Nullable] public char?     IsMaintSch             { get; set; } // nvarchar(1)
		[Column("CUST_NAME"),                    Nullable] public string    CustName               { get; set; } // nvarchar(500)
		[Column("ONLINF_OFLINE_ALIAS"),          Nullable] public string    OnlinfOflineAlias      { get; set; } // nvarchar(100)
		[Column("CUS_PHONE"),                    Nullable] public string    CusPhone               { get; set; } // nvarchar(100)
		[Column("CUS_FAX"),                      Nullable] public string    CusFax                 { get; set; } // nvarchar(50)
		[Column("CUS_MOBILE"),                   Nullable] public string    CusMobile              { get; set; } // nvarchar(100)
		[Column("CUS_EMAIL"),                    Nullable] public string    CusEmail               { get; set; } // nvarchar(100)
		[Column("CUS_ADDRESS"),                  Nullable] public string    CusAddress             { get; set; } // nvarchar(500)
		[Column("CUS_TAX"),                      Nullable] public string    CusTax                 { get; set; } // nvarchar(100)
		[Column("TAX_TYPE_CUST"),                Nullable] public char?     TaxTypeCust            { get; set; } // nvarchar(1)
		[Column("Q_SEQ_A"),                      Nullable] public decimal?  QSeqA                  { get; set; } // decimal(18, 0)
		[Column("Q_BRANCH_ID_A"),                Nullable] public decimal?  QBranchIdA             { get; set; } // decimal(18, 0)
		[Column("Q_TYPE_A"),                     Nullable] public decimal?  QTypeA                 { get; set; } // decimal(18, 0)
		[Column("CHECK_LIST_PATH_A"),            Nullable] public string    CheckListPathA         { get; set; } // nvarchar(1000)
		[Column("FILE_PATH_A"),                  Nullable] public string    FilePathA              { get; set; } // nvarchar(1000)
		[Column("CHASSI_TR_DATE"),               Nullable] public DateTime? ChassiTrDate           { get; set; } // date
		[Column("PLATE_NO"),                     Nullable] public string    PlateNo                { get; set; } // nvarchar(100)
		[Column("MODEL_DESC"),                   Nullable] public string    ModelDesc              { get; set; } // nvarchar(100)
		[Column("MADE_YEAR"),                    Nullable] public decimal?  MadeYear               { get; set; } // decimal(18, 0)
	}

	[Table(Schema="dbo", Name="SurveyDetails")]
	public partial class SurveyDetail
	{
		[PrimaryKey, Identity   ] public int    Id           { get; set; } // int
		[Column,        Nullable] public string SurveyNo     { get; set; } // varchar(350)
		[Column,        Nullable] public string QuestionDesc { get; set; } // varchar(450)
		[Column,        Nullable] public string Answer       { get; set; } // varchar(450)
		[Column,     NotNull    ] public int    QuestionId   { get; set; } // int
		[Column,     NotNull    ] public int    OptionId     { get; set; } // int
	}

	[Table(Schema="dbo", Name="SurveyMaster")]
	public partial class SurveyMaster
	{
		[Column(),           PrimaryKey,  Identity] public int       Id            { get; set; } // int
		[Column(),              Nullable          ] public string    SurveyNo      { get; set; } // varchar(350)
		[Column(),              Nullable          ] public string    CustomerIp    { get; set; } // varchar(255)
		[Column(),              Nullable          ] public DateTime? CreationUtc   { get; set; } // datetime
		[Column(),              Nullable          ] public DateTime? UpdateUtc     { get; set; } // datetime
		[Column(),           NotNull              ] public bool      IsDone        { get; set; } // bit
		[Column(),              Nullable          ] public string    Mobile        { get; set; } // varchar(50)
		[Column(),              Nullable          ] public string    CustomerName  { get; set; } // nvarchar(150)
		[Column(),              Nullable          ] public string    City          { get; set; } // nvarchar(50)
		[Column(),              Nullable          ] public int?      Age           { get; set; } // int
		[Column(),              Nullable          ] public string    Email         { get; set; } // varchar(50)
		[Column(),              Nullable          ] public string    Gender        { get; set; } // varchar(50)
		[Column(),              Nullable          ] public string    Car           { get; set; } // nvarchar(150)
		[Column(),              Nullable          ] public string    Comment       { get; set; } // nvarchar(max)
		[Column(),              Nullable          ] public string    RefNo         { get; set; } // varchar(150)
		[Column(),              Nullable          ] public string    SmsBody       { get; set; } // nvarchar(max)
		[Column(),              Nullable          ] public DateTime? SmsSentDate   { get; set; } // datetime
		[Column(),              Nullable          ] public bool?     SmsDone       { get; set; } // bit
		[Column(),           NotNull              ] public bool      Processed     { get; set; } // bit
		[Column("isReSent"),    Nullable          ] public bool?     IsReSent      { get; set; } // bit
		[Column(),              Nullable          ] public DateTime? SmsReSentDate { get; set; } // datetime
		[Column(),              Nullable          ] public string    SmsBodyReSent { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="SurveyQuestions")]
	public partial class SurveyQuestion
	{
		[PrimaryKey, NotNull    ] public int    Id           { get; set; } // int
		[Column,        Nullable] public string QuestionBody { get; set; } // nvarchar(500)
		[Column,        Nullable] public int?   OverallRate  { get; set; } // int
	}

	[Table(Schema="dbo", Name="SurveyQuestionOptions")]
	public partial class SurveyQuestionOption
	{
		[PrimaryKey, Identity] public int    Id          { get; set; } // int
		[Column,     NotNull ] public int    QuestionId  { get; set; } // int
		[Column,     NotNull ] public string OptionValue { get; set; } // nvarchar(50)
		[Column,     NotNull ] public int    OptionRate  { get; set; } // int
	}

	[Table(Schema="dbo", Name="vwContacts", IsView=true)]
	public partial class VwContact
	{
		[Column("CUS_MOBILE"), Nullable] public string CusMobile { get; set; } // nvarchar(100)
		[Column("CUS_NAME"),   Nullable] public string CusName   { get; set; } // nvarchar(500)
	}

	[Table(Schema="dbo", Name="vwContactSales", IsView=true)]
	public partial class VwContactSale
	{
		[Column("CUS_MOBILE"),   Nullable] public string   CusMobile   { get; set; } // nvarchar(100)
		[Column("CUS_NAME"),     Nullable] public string   CusName     { get; set; } // nvarchar(500)
		[Column("TOTAL_AMOUNT"), Nullable] public decimal? TotalAmount { get; set; } // decimal(18, 0)
	}

	[Table(Schema="dbo", Name="vwQuestionDefaultOption", IsView=true)]
	public partial class VwQuestionDefaultOption
	{
		[Column, NotNull    ] public int    QuestionId      { get; set; } // int
		[Column,    Nullable] public int?   DefaultOptionId { get; set; } // int
		[Column,    Nullable] public string OptionValue     { get; set; } // nvarchar(50)
	}

	[Table(Schema="dbo", Name="vwSurveyRegister", IsView=true)]
	public partial class VwSurveyRegister
	{
		[Column,    Nullable] public string    CustomerName { get; set; } // nvarchar(150)
		[Column,    Nullable] public string    Mobile       { get; set; } // varchar(50)
		[Column, NotNull    ] public string    City         { get; set; } // nvarchar(50)
		[Column, NotNull    ] public int       Age          { get; set; } // int
		[Column, NotNull    ] public string    Comment      { get; set; } // nvarchar(max)
		[Column,    Nullable] public int?      SumRate      { get; set; } // int
		[Column,    Nullable] public string    BranchName   { get; set; } // nvarchar(100)
		[Column,    Nullable] public string    EmpName      { get; set; } // nvarchar(200)
		[Column,    Nullable] public string    PlateNo      { get; set; } // nvarchar(100)
		[Column,    Nullable] public decimal?  SEQ          { get; set; } // decimal(18, 0)
		[Column,    Nullable] public decimal?  McSeq        { get; set; } // decimal(18, 0)
		[Column,    Nullable] public DateTime? SmsSentDate  { get; set; } // datetime
		[Column,    Nullable] public string    BranchEmail  { get; set; } // nvarchar(500)
		[Column,    Nullable] public string    RefNo        { get; set; } // varchar(150)
		[Column, NotNull    ] public bool      Processed    { get; set; } // bit
		[Column,    Nullable] public string    SurveyNo     { get; set; } // varchar(350)
		[Column,    Nullable] public DateTime? UpdateUtc    { get; set; } // datetime
		[Column,    Nullable] public string    Car          { get; set; } // nvarchar(150)
	}

	[Table(Schema="dbo", Name="vwSurveySumRate", IsView=true)]
	public partial class VwSurveySumRate
	{
		[Column, Nullable] public string SurveyNo { get; set; } // varchar(350)
		[Column, Nullable] public int?   SumRate  { get; set; } // int
	}

	public static partial class MizeCRMDBStoredProcedures
	{
		#region ReportCustomersSurveyData

		public static IEnumerable<ReportCustomersSurveyDataResult> ReportCustomersSurveyData(this MizeCRMDB dataConnection)
		{
			return dataConnection.QueryProc<ReportCustomersSurveyDataResult>("[dbo].[Report_CustomersSurveyData]");
		}

		public partial class ReportCustomersSurveyDataResult
		{
			public string   CustomerName  { get; set; }
			public string   Mobile        { get; set; }
			public string   Comment       { get; set; }
			public int?     SumRate       { get; set; }
			public string   BranchName    { get; set; }
			public string   EmpName       { get; set; }
			public string   Car           { get; set; }
			public decimal? SEQ           { get; set; }
			public string   SmsSentDate   { get; set; }
			public string   CustomerReply { get; set; }
			public string   QuestionDesc  { get; set; }
			public string   OptionValue   { get; set; }
			public int?     OptionRate    { get; set; }
		}

		#endregion

		#region SpReBUILDJobOrder

		public static int SpReBUILDJobOrder(this MizeCRMDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[SP_reBUILD_JOB_ORDER]");
		}

		#endregion

		#region GenerateSurveysForMizeCustomers

		public static int GenerateSurveysForMizeCustomers(this MizeCRMDB dataConnection, int? @daysToback)
		{
			var parameters = new []
			{
				new DataParameter("@daysToback", @daysToback, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[GenerateSurveysForMizeCustomers]", parameters);
		}

		#endregion

		#region GetSurveyMasterRegister

		public static IEnumerable<VwSurveyRegister> GetSurveyMasterRegister(this MizeCRMDB dataConnection, DateTime? @fromDate, DateTime? @toDate)
		{
			var parameters = new []
			{
				new DataParameter("@fromDate", @fromDate, LinqToDB.DataType.Date),
				new DataParameter("@toDate",   @toDate,   LinqToDB.DataType.Date)
			};

			return dataConnection.QueryProc<VwSurveyRegister>("[dbo].[GetSurveyMasterRegister]", parameters);
		}

		#endregion

		#region GetContactsSalesFromTo

		public static IEnumerable<VwContactSale> GetContactsSalesFromTo(this MizeCRMDB dataConnection, DateTime? @fromDate, DateTime? @toDate, string @cus_mobile)
		{
			var parameters = new []
			{
				new DataParameter("@fromDate",   @fromDate,   LinqToDB.DataType.Date),
				new DataParameter("@toDate",     @toDate,     LinqToDB.DataType.Date),
				new DataParameter("@cus_mobile", @cus_mobile, LinqToDB.DataType.VarChar)
				{
					Size = 50
				}
			};

			return dataConnection.QueryProc<VwContactSale>("[dbo].[GetContactsSalesFromTo]", parameters);
		}

		#endregion

		#region GetContactMCards

		public static IEnumerable<GetContactMCardsResult> GetContactMCards(this MizeCRMDB dataConnection, string @customerMobile)
		{
			var parameters = new []
			{
				new DataParameter("@customerMobile", @customerMobile, LinqToDB.DataType.VarChar)
				{
					Size = 100
				}
			};

			return dataConnection.QueryProc<GetContactMCardsResult>("[dbo].[GetContactMCards]", parameters);
		}

		public partial class GetContactMCardsResult
		{
			public string   CUS_MOBILE   { get; set; }
			public string   CUS_NAME     { get; set; }
			public decimal? YEAR_CODE    { get; set; }
			public decimal? BRANCH_ID    { get; set; }
			public string   BRANCH_NAME  { get; set; }
			public decimal? JOB_CARD_NO  { get; set; }
			public string   TR_DATE      { get; set; }
			public decimal? ADV_CODE     { get; set; }
			public string   NAME         { get; set; }
			public string   CHASSIS_NO   { get; set; }
			public string   OPEN_DATE    { get; set; }
			public string   CLOSE_DATE   { get; set; }
			public string   PLATE_NO     { get; set; }
			public string   MODEL_DESC   { get; set; }
			public string   SER          { get; set; }
			public decimal? TOTAL_AMOUNT { get; set; }
		}

		#endregion

		#region GetContactsMaster

		public static IEnumerable<GetContactsMasterResult> GetContactsMaster(this MizeCRMDB dataConnection, string @searchKey)
		{
			var parameters = new []
			{
				new DataParameter("@searchKey", @searchKey, LinqToDB.DataType.VarChar)
				{
					Size = 100
				}
			};

			return dataConnection.QueryProc<GetContactsMasterResult>("[dbo].[GetContactsMaster]", parameters);
		}

		public partial class GetContactsMasterResult
		{
			public string   CUS_MOBILE          { get; set; }
			public string   CUS_NAME            { get; set; }
			public decimal? YEAR_CODE           { get; set; }
			public decimal? BRANCH_ID           { get; set; }
			public string   BRANCH_NAME         { get; set; }
			public decimal? JOB_CARD_NO         { get; set; }
			public string   TR_DATE             { get; set; }
			public decimal? ADV_CODE            { get; set; }
			public string   NAME                { get; set; }
			public string   CHASSIS_NO          { get; set; }
			public string   OPEN_DATE           { get; set; }
			public string   CLOSE_DATE          { get; set; }
			public string   PLATE_NO            { get; set; }
			public string   MODEL_DESC          { get; set; }
			public decimal? TOTAL_AMOUNT        { get; set; }
			public decimal? TOTAL_AMOUNT_LAST90 { get; set; }
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Appointment Find(this ITable<Appointment> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Complaint Find(this ITable<Complaint> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ComplaintHistory Find(this ITable<ComplaintHistory> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ContactLoyaltyPointsSyncHistory Find(this ITable<ContactLoyaltyPointsSyncHistory> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static SurveyDetail Find(this ITable<SurveyDetail> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static SurveyMaster Find(this ITable<SurveyMaster> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static SurveyQuestion Find(this ITable<SurveyQuestion> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static SurveyQuestionOption Find(this ITable<SurveyQuestionOption> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
