//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels.MZReports
{
	/// <summary>
	/// Database       : MZReports
	/// Data Source    : sql.mizegroup.com
	/// Server Version : 10.50.6220
	/// </summary>
	public partial class MZReportsDB : LinqToDB.Data.DataConnection
	{
		public ITable<MscSalesAndTarget>   MscSalesAndTargets   { get { return this.GetTable<MscSalesAndTarget>(); } }
		public ITable<SaBranchsTarget>     SaBranchsTargets     { get { return this.GetTable<SaBranchsTarget>(); } }
		public ITable<VwJOBOrderSparePart> VwJOBOrderSpareParts { get { return this.GetTable<VwJOBOrderSparePart>(); } }
		public ITable<VwVEHICLEAchieved>   VwVEHICLEAchieveds   { get { return this.GetTable<VwVEHICLEAchieved>(); } }

		public MZReportsDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MZReportsDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MZReportsDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MZReportsDB(LinqToDBConnectionOptions<MZReportsDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="MSC_SALES_AND_TARGET")]
	public partial class MscSalesAndTarget
	{
		[Column("BRANCH_ID"),     NotNull    ] public decimal  BranchId    { get; set; } // decimal(18, 0)
		[Column("NET_INCL_TAX"),     Nullable] public decimal? NetInclTax  { get; set; } // decimal(18, 2)
		[Column("NET_EXCL_TAX"),     Nullable] public decimal? NetExclTax  { get; set; } // decimal(18, 2)
		[Column("SP_INCL_TAX"),      Nullable] public decimal? SpInclTax   { get; set; } // decimal(18, 2)
		[Column("SP_EXCL_TAX"),      Nullable] public decimal? SpExclTax   { get; set; } // decimal(18, 2)
		[Column("SP_GP"),            Nullable] public decimal? SpGp        { get; set; } // decimal(18, 2)
		[Column("GP_PERC"),          Nullable] public decimal? GpPerc      { get; set; } // decimal(18, 2)
		[Column("V_COUNT"),          Nullable] public int?     VCount      { get; set; } // int
		[Column("TARGET_VAL"),       Nullable] public decimal? TargetVal   { get; set; } // decimal(18, 0)
		[Column("TAR_PERC"),         Nullable] public decimal? TarPerc     { get; set; } // decimal(18, 2)
		[Column("BRANCH_NAME"),      Nullable] public string   BranchName  { get; set; } // nvarchar(250)
		[Column("SP_TARGET_VAL"),    Nullable] public decimal? SpTargetVal { get; set; } // decimal(18, 0)
		[Column("SP_TAR_PERC"),      Nullable] public decimal? SpTarPerc   { get; set; } // decimal(18, 2)
	}

	[Table(Schema="dbo", Name="SA_BRANCHS_TARGET")]
	public partial class SaBranchsTarget
	{
		[Column("BRANCH_ID"),           NotNull    ] public decimal  BranchId          { get; set; } // decimal(18, 0)
		[Column("YEAR_ID"),             NotNull    ] public decimal  YearId            { get; set; } // decimal(18, 0)
		[Column("MONTH_ID"),            NotNull    ] public decimal  MonthId           { get; set; } // decimal(18, 0)
		[Column("TARGET_VAL"),             Nullable] public decimal? TargetVal         { get; set; } // decimal(18, 0)
		[Column("ONLINF_OFLINE_ALIAS"),    Nullable] public string   OnlinfOflineAlias { get; set; } // nvarchar(100)
		[Column("SP_TARGET_VAL"),          Nullable] public decimal? SpTargetVal       { get; set; } // decimal(18, 0)
	}

	[Table(Schema="dbo", Name="vwJOB_ORDER_SPARE_PARTS", IsView=true)]
	public partial class VwJOBOrderSparePart
	{
		[Column("BRANCH_ID"), NotNull    ] public decimal  BranchId { get; set; } // decimal(18, 0)
		[Column("YEAR_CODE"), NotNull    ] public decimal  YearCode { get; set; } // decimal(18, 0)
		[Column(),            NotNull    ] public decimal  SEQ      { get; set; } // decimal(18, 0)
		[Column("SP_NET"),       Nullable] public decimal? SpNet    { get; set; } // decimal(38, 0)
		[Column("TOT_COST"),     Nullable] public decimal? TotCost  { get; set; } // decimal(38, 0)
		[Column("SP_GP"),        Nullable] public decimal? SpGp     { get; set; } // decimal(38, 0)
	}

	[Table(Schema="dbo", Name="vwVEHICLE_ACHIEVED", IsView=true)]
	public partial class VwVEHICLEAchieved
	{
		[Column("BRANCH_ID"), NotNull    ] public decimal BranchId { get; set; } // decimal(18, 0)
		[Column("YEAR_CODE"), NotNull    ] public decimal YearCode { get; set; } // decimal(18, 0)
		[Column("MONTH_NO"),     Nullable] public int?    MonthNo  { get; set; } // int
		[Column("V_COUNT"),      Nullable] public int?    VCount   { get; set; } // int
	}
}
